# Generated by Django 2.1.3 on 2018-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stem',
            name='score',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
