# Generated by Django 2.1.3 on 2018-12-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_stem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
