# Generated by Django 2.1.3 on 2018-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_score_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem',
            name='answer',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='stem',
            name='is_choicequestion',
            field=models.BooleanField(default=False),
        ),
    ]
