# Generated by Django 2.1.3 on 2018-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20181207_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grades',
            new_name='test_score',
        ),
        migrations.AlterField(
            model_name='testing',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
