# Generated by Django 2.1.3 on 2018-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20181208_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='test_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
