# Generated by Django 2.1.3 on 2018-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='start_testing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
