# Generated by Django 2.1.3 on 2018-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_testing_start_testing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='end_testing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
