# Generated by Django 2.1.3 on 2018-12-09 19:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_testing_end_testing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='test_time',
        ),
        migrations.AlterField(
            model_name='fillin',
            name='answer',
            field=models.CharField(max_length=50, null=True, verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='fillin',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='fillin',
            name='number',
            field=models.IntegerField(verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='option',
            name='comment',
            field=models.CharField(default='пишите описание выбора', max_length=40, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='score',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='ответ студента'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(verbose_name='балл'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='answer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='правильный ответ(для вопроса с выбором)'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='number',
            field=models.IntegerField(null=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='score',
            field=models.IntegerField(verbose_name='балл'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='заглавие'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='quantityOfTask',
            field=models.IntegerField(default=0, verbose_name='количество задач'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='ранкинг'),
        ),
        migrations.AlterField(
            model_name='student',
            name='test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='end_testing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания тестирования'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='start_testing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время начала тестирования'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='заглавие'),
        ),
    ]
